language: node_js
node_js:
  - "11.3"
install:
  - npm ci
script:
  - npm run build
  - npm run lint
  - npm run coverage
  - npm run build:example
after_success:
  - cat ./coverage/*.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules # NPM packages
deploy:
  - provider: releases
    api_key:
      secure: R4xxz1QwZlkXP3jFKqCnIW/IdGCBpaKJ9dPm53PM1cHcovvIJtY/ZJXS+e1Vs1zwCODhj6AN7BjyysS/YLVs2SV7G9YgjZECKnINXVIGnNGefutWuKho2uXFBBU25pXe10/GjvadlJDA7lbAKJoL0mDi0RituksIx6K+rDheOSI=
    file: dist/react-ace.min.js
    skip_cleanup: true
    on:
      tags: true
      repo: securingsincity/react-ace
  - provider: npm
    email: james.hrisho@gmail.com
    api_key:
      secure: "imtQDr4elRc6jwmWV7SIzuuFE5BOvrLydEuUZskeHRTQwbvVLZyEU1TRa/74UtNOnrXizf0Od2nCkDaTM7As+GA9r6T5dNoZfzENKXEwwkEk+TNLQp8l75z5jnDFBUq8gFi4Ad25Ys3TNovfvdCa3387h7m4IEKVoSrvaYaZfAA="
    skip_cleanup: true
    on:
      tags: true
      repo: securingsincity/react-ace
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: main
      repo: securingsincity/react-ace
    local_dir: example
